### PR TITLE
Heap Sort

### PR DESCRIPTION
**Pull request by aaryahjolia**
Added Heap sort

### CODE REVIEW

**Comment by aaryahjolia** [comment]
@StuntStorm

**Comment by harsh1x4** [comment]
Have you signed up for Hacktoberfest? If yes, can you please tell me by looking at the Hacktoberfest website that this repository is excluded or non-excluded?

**Comment by aaryahjolia** [comment]
> Have you signed up for Hacktoberfest? If yes, can you please tell me by looking at the Hacktoberfest website that this repository is excluded or non-excluded?

Non Excluded, You can contribute!

**Comment by harsh1x4** [comment]
Thank you✌

**Pull request merged**
